### ISSUE TITLE
Control-LED-strip-with-IR-Remote Library 

### ISSUE THREAD

**Issue by LandenBradley** [jxa13/Control-LED-strip-with-IR-Remote#1]
Hello, i need just the library as a zip file, it seams that Arduino IDE will not except the zip file containing the script and library. if you know a fix or could post just the library that would be great. Thanks

**Comment by 0xJxa** [comment]
Hi, the file was not meant to be added  into the IDE as Library, sorry if that wasn't clear.

I have amended the code and included the color libraries within the sketch so no extra steps are necessary now.

I hope this helps.

M
